---
title: 'EAE-1301: TEORIA DOS JOGOS'
author: Pedro Forquesato<br/>Departamento de Economia<br/>Faculdade de Economia, Administração, Contabilidade e Atuária<br/>Universidade de São Paulo
date: "2025/2"
output:
  prettydoc::html_pretty:
    toc: yes
    theme: architect
    urlcolor: green
  word_document: default
  html_document:
    toc: yes
    df_print: paged
  pdf_document: default
institute: Departamento de Economia<br/>Universidade de São Paulo
bibliography: ./eae0522_bib.bib
---

### Introdução

Teoria dos jogos é o ramo da *matemática aplicada* focado em modelar interações estratégicas entre jogadores racionais. O estudo desses modelos nos ajuda a pensar logicamente e desenvolver melhores estratégias de ação, além de esclarecer vários conceitos abstratos que são importantes na economia e em outras ciências humanas e sociais, como crenças e conhecimento, estratégias, reputação, credibilidade, incentivos e punição, cooperação, poder de barganha, entre outros.

O objetivo é que o aluno termine o curso conhecendo os principais jogos debatidos na teoria dos jogos e qual a sua importância, além de ter um bom entendimento dos conceitos de solução existentes e como computá-los.


### Objetivos de Aprendizagem

1. Reconhecer os principais jogos e teoremas da teoria dos jogos, sabendo os seus resultados e a razão de sua importância.
2. Aplicar os teoremas e algoritmos de solução da teoria dos jogos, resolvendo jogos de todos os principais tipos.
3. Avaliar a aplicabilidade de diferentes modelos da teoria dos jogos, julgando a sua condizência (positiva ou normativa) com o comportamento humano no mundo real.
4. Modelar situações de interações estratégicas entre agentes na forma de um jogo, criando modelos formalizados que nos informem sobre uma situação de interesse.

### Avaliação de Aprendizagem

1. **Duas provas:** 50% da nota cada. (Objetivos de aprendizagem 1 e 2.)
2. **Seis workshops (doze aulas)** de resolução *em sala* de exercícios. Para cada workshop com participação satisfatória, é adicionado (**crédito extra**) 0,3 na média, ou 0,15 de crédito parcial (1,8 pontos no máximo). (Objetivos de aprendizagem 1 a 4.)

<!--Caso o aluno participe satisfatoriamente de **todos** os workshops, a sua média pode ser escolhida por ele mesmo  por meio de uma autoavaliação (dado, evidentemente, a concordância do docente), *não sendo então necessária a realização das provas*. 

3. **Autoavaliação:** caso o aluno escolha (e possa escolher) esse método de avaliação, deve entregar um "portfolio" no fim do semestre de 1-3 páginas descrevendo o seu progresso, realizações e fazendo uma autoavaliação culminando na sua nota para o curso. Essa nota de autoavaliação será baseada em: (i) quantidade e dificuldade dos exercícios resolvidos nos workshops; (ii) participação em aula e nos workshops (por exemplo, ajudando os colegas); (iii) autoavaliação de seu progresso, conhecimento e dedicação na disciplina e em teoria dos jogos em geral. -->

Todas as médias serão arredondadas para cima (em relação à nota final no Moodle) a uma casa decimal (**e apenas isso**). Caso seja necessário para algum aluno, haverá uma prova de reavaliação, sendo a média final a média da primeira e segunda avaliações.

### Qualidade de Vida

Se você estiver passando por dificuldades: (i) se isso atrapalhar de alguma forma a sua capacidade de cursar a disciplina, fale comigo *antes do fim do curso* e acertaremos algo; (ii) contate os serviços de apoio da USP:

1. [Programa ECOS: Serviço de Escuta em Saúde Mental](https://prip.usp.br/programa-ecos/)
2. [Sistema USP de Acolhimento, Registro e Responsabilização para assédio, violência, discriminações e outras violações de direitos humanos (SUA)](https://prip.usp.br/institucional/sistema-usp-de-acolhimento-sua/), também por telefone: (11) 3091-5001.

### Docente

Meu nome é Pedro Forquesato, sou professor associado do Departamento de Economia da FEA/USP e pesquisador do [LabPub](https://labpub.fea.usp.br/). Mais informações sobre mim podem ser encontradas no [meu site](https://www.pedroforquesato.com). Minha área de atuação é em microeconomia aplicada, com ênfase em economia do setor público. Em 2025, leciono Princípios de Micro e Economia do Setor Público, além de Teoria dos Jogos (este curso), todos na graduação.

### Contato

Para questões específicas e individuais me mandem um [e-mail](mailto:pforquesato@usp.br). Se quiserem conversar pessoalmente, podem marcar um horário de atendimento no link disponível no Moodle. A minha sala é a 217 no FEA-2.

Por favor, sempre mandem e-mails claramente identificados, legíveis, **educados** e relativamente curtos. (Se o e-mail que vocês está escrevendo tem mais de 2 parágrafos, talvez valha a pena conversarmos pessoalmente.)

### Monitoria

Torçamos.

### Políticas e regulamentos

**Aulas.** As aulas são segundas-feiras das 21h20 às 23h00 e quintas-feiras das 19h30 às 21h10 (turma 2025221) na sala **XX** do FEA 1.

**Comunicação.** Toda a comunicação oficial por minha parte do curso será feita pelo [Moodle](https://edisciplinas.usp.br), incluindo notas, presenças e avisos. O curso assume que o aluno acessa frequentemente a plataforma e checa diariamente os e-mails recebidos.

**Faltas.** Pelo regulamento da USP, **participação em 70% das aulas é obrigatória** para aprovação na disciplina. Faltas serão desconsideradas apenas com atestado médico emitido pelo HU/USP ([Portaria GR 3740/2007](http://leginf.usp.br/?portaria=portaria-gr-no-3740-de-29-de-marco-de-2007)), com permissão especial para eventual Covid. 

O aluno pode faltar **no máximo** uma das duas provas (independentemente de atestado) e substituir a nota pela reaval, *sem precisar de justificativa*. (Naturalmente, a reaval cobre toda a matéria do curso.)

**Ética.** Todas as provas são **individuais e sem consulta**. "Cola" em alguma das provas resultará em reprovação sumária no curso. Listas (workshops) são realizadas em conjunto e com auxílio do docente e monitor, mas *devem ser escritas individualmente* e *em sala*. Listas copiadas implicarão renúncia de todas as atividades de crédito-extra do curso.

Note que essas punições ocorrerão sem prejuízo de eventual instauração de processo administrativo de acordo com o [Código de Ética da USP](http://leginf.usp.br/?resolucao=resolucao-no-4871-de-22-de-outubro-de-2001-3).

**Revisões.** Junto com a correção das provas, enviarei gabaritos delas. Pedidos de revisão ([Artigo 81, §§1-2 do RG/USP](https://leginf.usp.br/?resolucao=consolidada-resolucao-no-3745-de-19-de-outubro-de-1990#t5)) devem vir acompanhados de explicação precisa e especifica de onde a correção não seria coerente com o gabarito entregue e por que razão. Não há pedidos de revisão de média. 

**Reavaliação.** Alunos que tiverem mais de 70% de presença e nota entre 3 e 5 ([Portaria CoG 3583/1989](https://leginf.usp.br/?resolucao=resolucao-cog-no-3583-de-29-de-setembro-de1989)) podem fazer uma segunda avaliação (prova reaval), tendo assim a sua média final na disciplina como a média aritmética simples da média do curso e da nota da reaval.

**Outros.** Qualquer conflito com o docente que vocês não consigam (ou não queiram) resolver pessoalmente, recomendo que entrem em contato com a [Ouvidoria da FEA](https://www.fea.usp.br/fea/ouvidoria).

### Conteúdo programático, cronograma e bibliografia do curso

O curso está dividido em três partes. Cada parte consiste em três semanas de aulas teóricas explicando a matéria e como se dá a solução dessa classe de jogos, seguidas por duas semanas de workshops onde os conceitos são aplicados na resolução de uma lista de jogos.

Todas as datas abaixos são **estimativas** e **sujeitas a alteração** dependendo do andamento do semestre.

#### Parte 1: Jogos estáticos de informação completa

3 semanas de aulas [04/08, 06/08, 11/08, 13/08, 18/08 e 20/08]. [[Slides]](https://www.pedroforquesato.com/eae1301/eae1301-part-1.html) <br> **Bibliografia:** Tadelis, caps. 3, 4, 5 e 6. Osborne, cap. 11.

1. **Workshop 1:** Jogos em forma normal [25/08 e 27/08]. [[Lista 1]](https://www.pedroforquesato.com/files/eae1301-workshop1-2025.pdf)
2. **Workshop 2:** Outros jogos estáticos de informação completa [08/09 e 10/09]. [[Lista 2]](https://www.pedroforquesato.com/files/eae1301-workshop2-2025.pdf)

#### Parte 2: Jogos dinâmicos de informação completa

3 semanas de aulas [15/09, 17/09, 22/09, 24/09, 29/09 e 01/10]. [[Slides]](https://www.pedroforquesato.com/eae1301/eae1301-part-2.html) <br> **Bibliografia:** Tadelis, caps. 7, 8, 9, 10 e 11.

3. **Workshop 3:** Jogos dinâmicos de informação perfeita [06/10 e 08/10]. [[Lista 3]](https://www.pedroforquesato.com/files/eae1301-workshop3-2025.pdf)

Prova de meio-termo: **13/10**.

4. **Workshop 4:** Jogos dinâmicos de informação imperfeita [20/10 e 22/10]. [[Lista 4]](https://www.pedroforquesato.com/files/eae1301-workshop4-2025.pdf)

#### Parte 3: Jogos de informação incompleta

3 semanas de aulas [29/10, 03/11, 05/11, 10/11, 12/11]. [[Slides]](https://www.pedroforquesato.com/eae1301/eae1301-part-3.html) <br> **Bibliografia:** Tadelis, cap. 12, 15, 16, 17 e 18.

5. **Workshop 5:** Jogos bayesianos [17/11 e 19/11]. [[Lista 5]](https://www.pedroforquesato.com/files/eae1301-workshop5-2025.pdf)
6. **Workshop 6:** Refinamentos de equilíbrio [24/11 e 26/11]. [[Lista 6]](https://www.pedroforquesato.com/files/eae1301-workshop6-2025.pdf)

Prova final: **03/12**.

Reavaliação: **Jan/2026**.

### Referências

Os livros que vamos seguir de perto no curso são:

Tadelis, S. (2013). Game theory: an introduction. Princeton university press. <br>
Osborne, M. J. (2004). An introduction to game theory. New York: Oxford university press.

Mas teoria dos jogos é teoria dos jogos. Qualquer outro livro vai cobrir mais ou menos o mesmo material (mas às vezes com ênfase ou grau de formalização diferente). Alguns outros livros recomendados (em ordem de mais "fácil" para mais "difícil") são:

Gibbons, R. (1992). Game theory for applied economists. Princeton University Press. <br>
Binmore, K. (2007). Playing for real: a text on game theory. Oxford university press.<br>
Perea, A. (2012). Epistemic game theory: reasoning and choice. Cambridge University Press.<br>
Osborne, M. J., & Rubinstein, A. (1994). A course in game theory. MIT press. (\*) <br>
Maschler, M., Zamir, S., & Solan, E. (2020). Game theory. Cambridge University Press. (\*) <br>
Krishna, V. (2009). Auction theory. Academic press. (\*) <br>
Fudenberg, D., & Tirole, J. (1991). Game theory. MIT press. (\*)

Livros com (\*) são livros de pós-graduação. (Mas não precisamos ter medo de livros de pós-graduação!)

Caso o aluno queira complementar a leitura dos capítulos e a aula com vídeos ***completamente opcionais***, recomendo o curso do [Matthew Jackson e outros professores](https://www.game-theory-class.org/) (os vídeos podem ser acessados diretamente [aqui](https://www.youtube.com/@gametheoryonline)).

Outros vídeos no YouTube sugerido por alunos são o curso do [William Spaniel](https://www.youtube.com/playlist?list=PLKI1h_nAkaQoDzI4xDIXzx6U2ergFmedo) e [Selcuk Ozyurt](https://www.youtube.com/@selcukozyurt).


